create database boraMarcar;

use boraMarcar;

CREATE TABLE Usuario (
id INT PRIMARY KEY,
Nome_Razao_Social VARCHAR(70)  NOT NULL,
Telefone VARCHAR(50) NOT NULL,
Emaill VARCHAR(20) NOT NULL,
Senha VARCHAR(16) NOT NULL,
UNIQUE (Senha, id, Emaill),
Criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
Atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Pessoa (
CPF VARCHAR(12) UNIQUE NOT NULL,
Data_nascimento TIMESTAMP NOT NULL,
fk_Usuario_id INT,
PRIMARY KEY (CPF, fk_Usuario_id)
);

CREATE TABLE Estabelecimento (
CNPJ VARCHAR(20) UNIQUE NOT NULL,
Municipio VARCHAR(50) NOT NULL,
CEP VARCHAR(16) NOT NULL,
Estado VARCHAR(50) NOT NULL,
Tipo VARCHAR(20) NOT NULL,
fk_Usuario_id INT,
PRIMARY KEY (CNPJ, fk_Usuario_id)
);

CREATE TABLE Evento (
id INT PRIMARY KEY UNIQUE,
Horario TIMESTAMP NOT NULL,
Nome VARCHAR(50) NOT NULL,
Municipio VARCHAR(50) NOT NULL,
CEP VARCHAR(10) NOT NULL,
Estado VARCHAR(20) NOT NULL,
Publico BOOLEAN NOT NULL,
fk_Usuario_id INT,
Criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
Atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Comparece (
fk_Pessoa_CPF VARCHAR(12),
fk_Usuario_id INT,
fk_Evento_id INT,
PRIMARY KEY (fk_Usuario_id, fk_Evento_id),
Criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Sessao (
fk_Usuario_id INT PRIMARY KEY,
token VARCHAR(100) NOT NULL,
Criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE Pessoa ADD CONSTRAINT FK_Pessoa_2
FOREIGN KEY (fk_Usuario_id)
REFERENCES Usuario (id)
ON DELETE CASCADE;

ALTER TABLE Estabelecimento ADD CONSTRAINT FK_Estabelecimento_2
FOREIGN KEY (fk_Usuario_id)
REFERENCES Usuario (id)
ON DELETE CASCADE;

ALTER TABLE Evento ADD CONSTRAINT FK_Evento_2
FOREIGN KEY (fk_Usuario_id)
REFERENCES Usuario (id)
ON DELETE SET NULL;

ALTER TABLE Comparece ADD CONSTRAINT FK_Comparece_1
FOREIGN KEY (fk_Pessoa_CPF, fk_Usuario_id)
REFERENCES Pessoa (CPF, fk_Usuario_id);

ALTER TABLE Comparece ADD CONSTRAINT FK_Comparece_2
FOREIGN KEY (fk_Evento_id)
REFERENCES Evento (id);

ALTER TABLE Comparece ADD UNIQUE Comparece_Unique
(fk_Pessoa_CPF,fk_Usuario_id, fk_Evento_id);


ALTER TABLE Sessao ADD CONSTRAINT FK_Sessao_1
FOREIGN KEY (fk_Usuario_id)
REFERENCES Usuario (id);