create database boraMarcar;

use boraMarcar;

CREATE TABLE Usuario (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
nome VARCHAR(100)  NOT NULL,
telefone VARCHAR(100) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
senha VARCHAR(100) NOT NULL,
imagemId INT NOT NULL,
criadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
atualizadoEm DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Pessoa (
cpf VARCHAR(20) UNIQUE NOT NULL,
dataNascimento TIMESTAMP NOT NULL,
usuarioId INT,
PRIMARY KEY (cpf, usuarioId)
);

CREATE TABLE Estabelecimento (
cnpj VARCHAR(20) UNIQUE NOT NULL,
tipo VARCHAR(100) NOT NULL,
usuarioId INT,
enderecoId INT,
PRIMARY KEY (CNPJ, usuarioId)
);

CREATE TABLE Evento (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
horario TIMESTAMP NOT NULL,
nome VARCHAR(100) NOT NULL,
descricao varchar(100) NOT NULL,
publico BOOLEAN NOT NULL,
usuarioId INT NOT NULL,
enderecoId INT NOT NULL,
imagemId INT NOT NULL,
criadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
atualizadoEm DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Imagem (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
arquivo LONGBLOB NOT NULL,
nome VARCHAR (200) NOT NULL,
tipo VARCHAR(50) NOT NULL
);

CREATE TABLE Endereco (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
logradouro VARCHAR(200) NOT NULL,
complemento VARCHAR (200),
cep VARCHAR(15) NOT NULL,
municipio VARCHAR(100) NOT NULL,
estado VARCHAR(100) NOT NULL
);

CREATE TABLE Comparece (
usuarioId INT NOT NULL,
eventoId INT NOT NULL,
presente BOOLEAN NOT NULL,
PRIMARY KEY (usuarioId, eventoId),
criadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
atualizadoEm DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Sessao (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
usuarioId INT,
token VARCHAR(100) NOT NULL,
criadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
atualizadoEm DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sessaoadmin (
id INT NOT NULL AUTO_INCREMENT,
token VARCHAR(100) NOT NULL,
PRIMARY KEY (id),
UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE
);

ALTER TABLE Usuario ADD CONSTRAINT FK_Usuario_1
FOREIGN KEY (imagemId)
REFERENCES Imagem (id)
ON DELETE CASCADE;

ALTER TABLE Pessoa ADD CONSTRAINT FK_Pessoa_1
FOREIGN KEY (usuarioId)
REFERENCES Usuario (id)
ON DELETE CASCADE;

ALTER TABLE Estabelecimento ADD CONSTRAINT FK_Estabelecimento_1
FOREIGN KEY (usuarioId)
REFERENCES Usuario (id)
ON DELETE CASCADE;

ALTER TABLE Evento ADD CONSTRAINT FK_Evento_1
FOREIGN KEY (usuarioId)
REFERENCES Usuario (id)
ON DELETE CASCADE;

ALTER TABLE Evento ADD CONSTRAINT FK_Evento_2
FOREIGN KEY (imagemId)
REFERENCES Imagem (id)
ON DELETE CASCADE;

ALTER TABLE Comparece ADD CONSTRAINT FK_Comparece_1
FOREIGN KEY (usuarioId)
REFERENCES Pessoa (usuarioId);

ALTER TABLE Comparece ADD CONSTRAINT FK_Comparece_2
FOREIGN KEY (eventoId)
REFERENCES Evento (id);

ALTER TABLE Comparece ADD UNIQUE Comparece_Unique
(usuarioId, eventoId);


ALTER TABLE Sessao ADD CONSTRAINT FK_Sessao_1
FOREIGN KEY (usuarioId)
REFERENCES Usuario (id);

ALTER TABLE Estabelecimento ADD CONSTRAINT FK_Endereco_1
FOREIGN KEY (enderecoId)
REFERENCES Endereco (id)
ON DELETE CASCADE;

ALTER TABLE Evento ADD CONSTRAINT FK_Endereco_2
FOREIGN KEY (enderecoId)
REFERENCES Endereco (id)
ON DELETE CASCADE;